name: GitHub Actions

on:
  schedule:
    - cron: '* * * * *'  # Run every minute

jobs:
  build:
    name: GitHub Actions
    runs-on: ubuntu-latest
    
    steps:
      - name: Make HTTP request to API endpoint
        uses: actions/http-client@v1
        with:
          args: |
            POST https://nfpage.vercel.app/api/subscriptionChecker