on:
  schedule:
    - cron: '* * * * *'

jobs:
  explore_github_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Make request to API
        run: |
          curl -X GET 'https://nfpage.vercel.app/api/subscriptionChecker'